<?php

/**
 * @file
 * Primary module hooks for Registration Email Whitelist module.
 */

function registration_email_whitelist_validator(&$form, \Drupal\Core\Form\FormState $form_state) {
    $email = $form_state->getValue('mail');

    $email_service = \Drupal::service('registration_email_whitelist.email_service');
    $email_from_db = $email_service->getEmailFromWhitelist($email);
    if (empty($email_from_db)) {
        $form_state->setErrorByName(
            'mail',
            t('E-mail is not on the white list.'),
        );
    }
}

function  registration_email_whitelist_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
    
    if ($form_id === 'user_register_form') {
        $form['#validate'][] = 'registration_email_whitelist_validator';
    }   
}

